# Project 3: Data Cleaning - Tidy up messy Datasets (Movies Dataset)

# Project Brief for Self-Coders

Here you´ll have the opportunity to code major parts of Project 3 on your own. If you need any help or inspiration, have a look at the Videos or the Jupyter Notebook with the full code. <br> <br>
Keep in mind that it´s all about __getting the right results/conclusions__. It´s not about finding the identical code. Things can be coded in many different ways. Even if you come to the same conclusions, it´s very unlikely that we have the very same code.

## First Steps

1. __Load__ and __inspect__ the messy dataset __movies_metadata.csv__. Identify columns with nested / stringified json data.

In [2]:
import pandas as pd
import json
import numpy as np

In [3]:
df_raw=pd.read_csv("movies_metadata.csv")
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

C:\Users\Dell-G3\AppData\Local\Temp\ipykernel_8804\2656496264.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df_raw=pd.read_csv("movies_metadata.csv")

In [4]:
df_raw.describe()

            revenue       runtime  vote_average    vote_count
count  4.546000e+04  45203.000000  45460.000000  45460.000000
mean   1.120935e+07     94.128199      5.618207    109.897338
std    6.433225e+07     38.407810      1.924216    491.310374
min    0.000000e+00      0.000000      0.000000      0.000000
25%    0.000000e+00     85.000000      5.000000      3.000000
50%    0.000000e+00     95.000000      6.000000     10.000000
75%    0.000000e+00    107.000000      6.800000     34.000000
max    2.787965e+09   1256.000000     10.000000  14075.000000

## Dropping irrelevant Columns

2. __Drop__ the irrelevant columns 'adult', 'imdb_id', 'original_title', 'video' and 'homepage'.

In [5]:
df_dropped=df_raw.drop(['adult','imdb_id', 'original_title', 'video','homepage'], axis=1)

## How to handle stringified JSON columns

3. __Evaluate__ Python Expressions in the stringified columns ["belongs_to_collection", "genres", "production_countries", "production_companies", "spoken_languages"] and __remove quotes__ ("") where possible.

In [9]:
import ast
df_evaluated=df_dropped.copy()
df_evaluated['belongs_to_collection']=df_evaluated['belongs_to_collection'].apply(lambda x: ast.literal_eval(x) if isinstance(x,str) else x)
df_evaluated['genres']=df_evaluated['genres'].apply(lambda x: eval(x) if isinstance(x,str) else x)
df_evaluated['production_countries']=df_evaluated['production_countries'].apply(lambda x: eval(x) if isinstance(x,str) else x)
df_evaluated['production_companies']=df_evaluated['production_companies'].apply(lambda x: eval(x) if isinstance(x,str) else x)
df_evaluated['spoken_languages']=df_evaluated['spoken_languages'].apply(lambda x: eval(x) if isinstance(x,str) else x)
df_evaluated

,belongs_to_collection,budget,genres,id,original_language,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,7.7,5415.0
1,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844,en,When siblings Judy and Peter discover an encha...,17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,6.9,2413.0
2,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602,en,A family wedding reignites the ancient feud be...,11.7129,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5,92.0
3,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357,en,"Cheated on, mistreated and stepped on, the wom...",3.859495,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,6.1,34.0
4,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",11862,en,Just when George Banks has recovered from his ...,8.387519,/e64sOI48hQXyru7naBFyssKFxVd.jpg,"[{'name': 'Sandollar Productions', 'id': 5842}...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",439050,fa,Rising and falling between a man and woman.,0.072051,/jldsYflnId4tTWPx8es3uzsB1I8.jpg,[],"[{'iso_3166_1': 'IR', 'name': 'Iran'}]",NaN,0.0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,4.0,1.0
45462,NaN,0,"[{'id': 18, 'name': 'Drama'}]",111109,tl,An artist struggles to finish his work while a...,0.178241,/xZkmxsNmYXJbKVsTRLLx3pqGHx7.jpg,"[{'name': 'Sine Olivia', 'id': 19653}]","[{'iso_3166_1': 'PH', 'name': 'Philippines'}]",2011-11-17,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,9.0,3.0
45463,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",67758,en,"When one of her hits goes wrong, a professiona...",0.903007,/d5bX92nDsISNhu3ZT69uHwmfCGw.jpg,"[{'name': 'American World Pictures', 'id': 6165}]","[{'iso_3166_1': 'US', 'name': 'United States o...",2003-08-01,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,3.8,6.0
45464,NaN,0,[],227506,en,"In a small town live two brothers, one a minis...",0.003503,/aorBPO7ak8e8iJKT5OcqYxU3jlK.jpg,"[{'name': 'Yermoliev', 'id': 88753}]","[{'iso_3166_1': 'RU', 'name': 'Russia'}]",1917-10-21,0.0,87.0,[],Released,NaN,Satan Triumphant,0.0,0.0
45465,NaN,0,[],461257,en,50 years after decriminalisation of homosexual...,0.163015,/s5UkZt6NTsrS7ZF0Rh8nzupRlIU.jpg,[],"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",2017-06-09,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,0.0,0.0

## How to flatten nested Columns

4. __Extract__ only the __collection name__ from the column "belongs_to_collection" and __overwrite__ "belongs_to_collection". <br> For example: The value in the first row (Toy Story) should be 'Toy Story Collection'.

In [31]:
df_flattened=df_evaluated.copy()
df_flattened['belongs_to_collection']=df_evaluated['belongs_to_collection'].apply(lambda x: x.get('name') if isinstance(x,dict) else x)
df_flattened

,belongs_to_collection,budget,genres,id,original_language,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,Toy Story Collection,30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,7.7,5415.0
1,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844,en,When siblings Judy and Peter discover an encha...,17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,6.9,2413.0
2,Grumpy Old Men Collection,0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602,en,A family wedding reignites the ancient feud be...,11.7129,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5,92.0
3,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357,en,"Cheated on, mistreated and stepped on, the wom...",3.859495,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,6.1,34.0
4,Father of the Bride Collection,0,"[{'id': 35, 'name': 'Comedy'}]",11862,en,Just when George Banks has recovered from his ...,8.387519,/e64sOI48hQXyru7naBFyssKFxVd.jpg,"[{'name': 'Sandollar Productions', 'id': 5842}...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",439050,fa,Rising and falling between a man and woman.,0.072051,/jldsYflnId4tTWPx8es3uzsB1I8.jpg,[],"[{'iso_3166_1': 'IR', 'name': 'Iran'}]",NaN,0.0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,4.0,1.0
45462,NaN,0,"[{'id': 18, 'name': 'Drama'}]",111109,tl,An artist struggles to finish his work while a...,0.178241,/xZkmxsNmYXJbKVsTRLLx3pqGHx7.jpg,"[{'name': 'Sine Olivia', 'id': 19653}]","[{'iso_3166_1': 'PH', 'name': 'Philippines'}]",2011-11-17,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,9.0,3.0
45463,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",67758,en,"When one of her hits goes wrong, a professiona...",0.903007,/d5bX92nDsISNhu3ZT69uHwmfCGw.jpg,"[{'name': 'American World Pictures', 'id': 6165}]","[{'iso_3166_1': 'US', 'name': 'United States o...",2003-08-01,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,3.8,6.0
45464,NaN,0,[],227506,en,"In a small town live two brothers, one a minis...",0.003503,/aorBPO7ak8e8iJKT5OcqYxU3jlK.jpg,"[{'name': 'Yermoliev', 'id': 88753}]","[{'iso_3166_1': 'RU', 'name': 'Russia'}]",1917-10-21,0.0,87.0,[],Released,NaN,Satan Triumphant,0.0,0.0
45465,NaN,0,[],461257,en,50 years after decriminalisation of homosexual...,0.163015,/s5UkZt6NTsrS7ZF0Rh8nzupRlIU.jpg,[],"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",2017-06-09,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,0.0,0.0

5. __Extract__ all __genre names__ from the column "genres" and __overwrite__ "genres". If a movie has more than one genre, __seperate genres by a pipe__ "|".<br>
For example: The value in the first row (Toy Story) should be 'Animation|Comedy|Family'.

In [32]:
def get_items_from_dicts(ls: list, key)->str:
    item_str=''
    for dict_ in ls:
        item_str+=dict_.get(key,'')+'|'
    return item_str.strip('|')
    
df_flattened['genres']=df_evaluated['genres'].apply(lambda x: get_items_from_dicts(x, 'name') if isinstance(x,list) else x)
df_flattened

,belongs_to_collection,budget,genres,id,original_language,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,Toy Story Collection,30000000,Animation|Comedy|Family,862,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,7.7,5415.0
1,NaN,65000000,Adventure|Fantasy|Family,8844,en,When siblings Judy and Peter discover an encha...,17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,6.9,2413.0
2,Grumpy Old Men Collection,0,Romance|Comedy,15602,en,A family wedding reignites the ancient feud be...,11.7129,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5,92.0
3,NaN,16000000,Comedy|Drama|Romance,31357,en,"Cheated on, mistreated and stepped on, the wom...",3.859495,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,6.1,34.0
4,Father of the Bride Collection,0,Comedy,11862,en,Just when George Banks has recovered from his ...,8.387519,/e64sOI48hQXyru7naBFyssKFxVd.jpg,"[{'name': 'Sandollar Productions', 'id': 5842}...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,NaN,0,Drama|Family,439050,fa,Rising and falling between a man and woman.,0.072051,/jldsYflnId4tTWPx8es3uzsB1I8.jpg,[],"[{'iso_3166_1': 'IR', 'name': 'Iran'}]",NaN,0.0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,4.0,1.0
45462,NaN,0,Drama,111109,tl,An artist struggles to finish his work while a...,0.178241,/xZkmxsNmYXJbKVsTRLLx3pqGHx7.jpg,"[{'name': 'Sine Olivia', 'id': 19653}]","[{'iso_3166_1': 'PH', 'name': 'Philippines'}]",2011-11-17,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,9.0,3.0
45463,NaN,0,Action|Drama|Thriller,67758,en,"When one of her hits goes wrong, a professiona...",0.903007,/d5bX92nDsISNhu3ZT69uHwmfCGw.jpg,"[{'name': 'American World Pictures', 'id': 6165}]","[{'iso_3166_1': 'US', 'name': 'United States o...",2003-08-01,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,3.8,6.0
45464,NaN,0,,227506,en,"In a small town live two brothers, one a minis...",0.003503,/aorBPO7ak8e8iJKT5OcqYxU3jlK.jpg,"[{'name': 'Yermoliev', 'id': 88753}]","[{'iso_3166_1': 'RU', 'name': 'Russia'}]",1917-10-21,0.0,87.0,[],Released,NaN,Satan Triumphant,0.0,0.0
45465,NaN,0,,461257,en,50 years after decriminalisation of homosexual...,0.163015,/s5UkZt6NTsrS7ZF0Rh8nzupRlIU.jpg,[],"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",2017-06-09,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,0.0,0.0

6. __Extract__ all __spoken language names__ from the column "spoken_languages" and __overwrite__ "spoken_languages". If a movie has more than one spoken language, __seperate spoken languages by a pipe__ "|".<br>
For example: The value in the first row (Toy Story) should be 'English'.

In [33]:
df_flattened['spoken_languages']=df_evaluated['spoken_languages'].apply(lambda x: get_items_from_dicts(x, 'name') if isinstance(x,list) else x)
df_flattened

,belongs_to_collection,budget,genres,id,original_language,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,Toy Story Collection,30000000,Animation|Comedy|Family,862,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,373554033.0,81.0,English,Released,NaN,Toy Story,7.7,5415.0
1,NaN,65000000,Adventure|Fantasy|Family,8844,en,When siblings Judy and Peter discover an encha...,17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,262797249.0,104.0,English|Français,Released,Roll the dice and unleash the excitement!,Jumanji,6.9,2413.0
2,Grumpy Old Men Collection,0,Romance|Comedy,15602,en,A family wedding reignites the ancient feud be...,11.7129,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,0.0,101.0,English,Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5,92.0
3,NaN,16000000,Comedy|Drama|Romance,31357,en,"Cheated on, mistreated and stepped on, the wom...",3.859495,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,81452156.0,127.0,English,Released,Friends are the people who let you be yourself...,Waiting to Exhale,6.1,34.0
4,Father of the Bride Collection,0,Comedy,11862,en,Just when George Banks has recovered from his ...,8.387519,/e64sOI48hQXyru7naBFyssKFxVd.jpg,"[{'name': 'Sandollar Productions', 'id': 5842}...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-02-10,76578911.0,106.0,English,Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,NaN,0,Drama|Family,439050,fa,Rising and falling between a man and woman.,0.072051,/jldsYflnId4tTWPx8es3uzsB1I8.jpg,[],"[{'iso_3166_1': 'IR', 'name': 'Iran'}]",NaN,0.0,90.0,فارسی,Released,Rising and falling between a man and woman,Subdue,4.0,1.0
45462,NaN,0,Drama,111109,tl,An artist struggles to finish his work while a...,0.178241,/xZkmxsNmYXJbKVsTRLLx3pqGHx7.jpg,"[{'name': 'Sine Olivia', 'id': 19653}]","[{'iso_3166_1': 'PH', 'name': 'Philippines'}]",2011-11-17,0.0,360.0,,Released,NaN,Century of Birthing,9.0,3.0
45463,NaN,0,Action|Drama|Thriller,67758,en,"When one of her hits goes wrong, a professiona...",0.903007,/d5bX92nDsISNhu3ZT69uHwmfCGw.jpg,"[{'name': 'American World Pictures', 'id': 6165}]","[{'iso_3166_1': 'US', 'name': 'United States o...",2003-08-01,0.0,90.0,English,Released,A deadly game of wits.,Betrayal,3.8,6.0
45464,NaN,0,,227506,en,"In a small town live two brothers, one a minis...",0.003503,/aorBPO7ak8e8iJKT5OcqYxU3jlK.jpg,"[{'name': 'Yermoliev', 'id': 88753}]","[{'iso_3166_1': 'RU', 'name': 'Russia'}]",1917-10-21,0.0,87.0,,Released,NaN,Satan Triumphant,0.0,0.0
45465,NaN,0,,461257,en,50 years after decriminalisation of homosexual...,0.163015,/s5UkZt6NTsrS7ZF0Rh8nzupRlIU.jpg,[],"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",2017-06-09,0.0,75.0,English,Released,NaN,Queerama,0.0,0.0

7. __Extract__ all __production countries names__ from the column "production_countries" and __overwrite__ "production_countries". If a movie has more than one production country, __seperate production countries by a pipe__ "|".<br>
For example: The value in the first row (Toy Story) should be 'United States of America'.

In [34]:
df_flattened['production_countries']=df_evaluated['production_countries'].apply(lambda x: get_items_from_dicts(x, 'name') if isinstance(x,list) else x)
df_flattened

,belongs_to_collection,budget,genres,id,original_language,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,Toy Story Collection,30000000,Animation|Comedy|Family,862,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,"[{'name': 'Pixar Animation Studios', 'id': 3}]",United States of America,1995-10-30,373554033.0,81.0,English,Released,NaN,Toy Story,7.7,5415.0
1,NaN,65000000,Adventure|Fantasy|Family,8844,en,When siblings Judy and Peter discover an encha...,17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...",United States of America,1995-12-15,262797249.0,104.0,English|Français,Released,Roll the dice and unleash the excitement!,Jumanji,6.9,2413.0
2,Grumpy Old Men Collection,0,Romance|Comedy,15602,en,A family wedding reignites the ancient feud be...,11.7129,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...",United States of America,1995-12-22,0.0,101.0,English,Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5,92.0
3,NaN,16000000,Comedy|Drama|Romance,31357,en,"Cheated on, mistreated and stepped on, the wom...",3.859495,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,[{'name': 'Twentieth Century Fox Film Corporat...,United States of America,1995-12-22,81452156.0,127.0,English,Released,Friends are the people who let you be yourself...,Waiting to Exhale,6.1,34.0
4,Father of the Bride Collection,0,Comedy,11862,en,Just when George Banks has recovered from his ...,8.387519,/e64sOI48hQXyru7naBFyssKFxVd.jpg,"[{'name': 'Sandollar Productions', 'id': 5842}...",United States of America,1995-02-10,76578911.0,106.0,English,Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,NaN,0,Drama|Family,439050,fa,Rising and falling between a man and woman.,0.072051,/jldsYflnId4tTWPx8es3uzsB1I8.jpg,[],Iran,NaN,0.0,90.0,فارسی,Released,Rising and falling between a man and woman,Subdue,4.0,1.0
45462,NaN,0,Drama,111109,tl,An artist struggles to finish his work while a...,0.178241,/xZkmxsNmYXJbKVsTRLLx3pqGHx7.jpg,"[{'name': 'Sine Olivia', 'id': 19653}]",Philippines,2011-11-17,0.0,360.0,,Released,NaN,Century of Birthing,9.0,3.0
45463,NaN,0,Action|Drama|Thriller,67758,en,"When one of her hits goes wrong, a professiona...",0.903007,/d5bX92nDsISNhu3ZT69uHwmfCGw.jpg,"[{'name': 'American World Pictures', 'id': 6165}]",United States of America,2003-08-01,0.0,90.0,English,Released,A deadly game of wits.,Betrayal,3.8,6.0
45464,NaN,0,,227506,en,"In a small town live two brothers, one a minis...",0.003503,/aorBPO7ak8e8iJKT5OcqYxU3jlK.jpg,"[{'name': 'Yermoliev', 'id': 88753}]",Russia,1917-10-21,0.0,87.0,,Released,NaN,Satan Triumphant,0.0,0.0
45465,NaN,0,,461257,en,50 years after decriminalisation of homosexual...,0.163015,/s5UkZt6NTsrS7ZF0Rh8nzupRlIU.jpg,[],United Kingdom,2017-06-09,0.0,75.0,English,Released,NaN,Queerama,0.0,0.0

8. __Extract__ all __production companies names__ from the column "production_companies" and __overwrite__ "production_companies". If a movie has more than one production company, __seperate production companies by a pipe__ "|".<br>
For example: The value in the first row (Toy Story) should be 'Pixar Animation Studios'

In [35]:
df_flattened['production_companies']=df_evaluated['production_companies'].apply(lambda x: get_items_from_dicts(x, 'name') if isinstance(x,list) else x)
df_flattened

,belongs_to_collection,budget,genres,id,original_language,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,Toy Story Collection,30000000,Animation|Comedy|Family,862,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,Pixar Animation Studios,United States of America,1995-10-30,373554033.0,81.0,English,Released,NaN,Toy Story,7.7,5415.0
1,NaN,65000000,Adventure|Fantasy|Family,8844,en,When siblings Judy and Peter discover an encha...,17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,TriStar Pictures|Teitler Film|Interscope Commu...,United States of America,1995-12-15,262797249.0,104.0,English|Français,Released,Roll the dice and unleash the excitement!,Jumanji,6.9,2413.0
2,Grumpy Old Men Collection,0,Romance|Comedy,15602,en,A family wedding reignites the ancient feud be...,11.7129,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,Warner Bros.|Lancaster Gate,United States of America,1995-12-22,0.0,101.0,English,Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5,92.0
3,NaN,16000000,Comedy|Drama|Romance,31357,en,"Cheated on, mistreated and stepped on, the wom...",3.859495,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,Twentieth Century Fox Film Corporation,United States of America,1995-12-22,81452156.0,127.0,English,Released,Friends are the people who let you be yourself...,Waiting to Exhale,6.1,34.0
4,Father of the Bride Collection,0,Comedy,11862,en,Just when George Banks has recovered from his ...,8.387519,/e64sOI48hQXyru7naBFyssKFxVd.jpg,Sandollar Productions|Touchstone Pictures,United States of America,1995-02-10,76578911.0,106.0,English,Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,NaN,0,Drama|Family,439050,fa,Rising and falling between a man and woman.,0.072051,/jldsYflnId4tTWPx8es3uzsB1I8.jpg,,Iran,NaN,0.0,90.0,فارسی,Released,Rising and falling between a man and woman,Subdue,4.0,1.0
45462,NaN,0,Drama,111109,tl,An artist struggles to finish his work while a...,0.178241,/xZkmxsNmYXJbKVsTRLLx3pqGHx7.jpg,Sine Olivia,Philippines,2011-11-17,0.0,360.0,,Released,NaN,Century of Birthing,9.0,3.0
45463,NaN,0,Action|Drama|Thriller,67758,en,"When one of her hits goes wrong, a professiona...",0.903007,/d5bX92nDsISNhu3ZT69uHwmfCGw.jpg,American World Pictures,United States of America,2003-08-01,0.0,90.0,English,Released,A deadly game of wits.,Betrayal,3.8,6.0
45464,NaN,0,,227506,en,"In a small town live two brothers, one a minis...",0.003503,/aorBPO7ak8e8iJKT5OcqYxU3jlK.jpg,Yermoliev,Russia,1917-10-21,0.0,87.0,,Released,NaN,Satan Triumphant,0.0,0.0
45465,NaN,0,,461257,en,50 years after decriminalisation of homosexual...,0.163015,/s5UkZt6NTsrS7ZF0Rh8nzupRlIU.jpg,,United Kingdom,2017-06-09,0.0,75.0,English,Released,NaN,Queerama,0.0,0.0

9. __Inspect__ all columns above with value_counts(). Do you see anything strange? __Take reasonable measures__!

In [36]:
for col in df_flattened.columns:
    print(df_flattened[col].value_counts())
    print(str(df_flattened[col].dtype)+'\n')
#replace all empty strings for NaN
df_flattened.replace('',np.nan, inplace=True)
df_flattened

The Bowery Boys                       29
Totò Collection                       27
James Bond Collection                 26
Zatôichi: The Blind Swordsman         26
The Carry On Collection               25
                                      ..
No Good Middle-Aged Yakuza Trilogy     1
The Spiritual Boxer Collection         1
East Side Kids                         1
Seed Collection                        1
Red Lotus Collection                   1
Name: belongs_to_collection, Length: 1698, dtype: int64
object

0           36573
5000000       286
10000000      259
20000000      243
2000000       242
            ...
923             1
72500000        1
2160000         1
4439832         1
1254040         1
Name: budget, Length: 1226, dtype: int64
object

Drama                              5000
Comedy                             3621
Documentary                        2723
                                   2442
Drama|Romance                      1301
                                   ...
Action|Drama|Comedy|Documentary       1
War|Drama|History|Thriller            1
Horror|Drama|History|Thriller         1
Comedy|Crime|Action|Drama             1
Family|Animation|Romance|Comedy       1
Name: genres, Length: 4069, dtype: int64
object

141971    3
168538    2
25541     2
15028     2
11115     2
         ..
72272     1
1549      1
10171     1
38996     1
461257    1
Name: id, Length: 45436, dtype: int64
object

en       32269
fr        2438
it        1529
ja        1350
de        1080
         ...
zu           1
qu           1
104.0        1
la           1
si           1
Name: original_language, Length: 92, dtype: int64
object

No overview found.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       133
No Overview                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                7
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           5
No movie overview available.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               3
A few funny little novels about different aspects of life.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 3
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ...
"Of Time and The City" is both a love song and a eulogy to the director's birthplace of Liverpool, England. It is also a response to memory, reflection and the experience of losing a sense of place as the skyline changes and time takes it toll. The visual content of the film consists largely of archival clips of Liverpool from the 1940s to the 1960s, their nostalgic charm darkened by accompanying music and by the counterpoint of Davies’ dry, at times dyspeptic, voice-over narration. His voice thickens with emotion as he recalls the delights of juvenile movie-going or the ritual of a holiday trip to New Brighton, across the River Mersey, and hardens with contempt when he turns his gaze on the hoopla surrounding Queen Elizabeth’s coronation in 1953.      1
We are in the year 1871. A journalist for Versailles Television broadcasts a soothing and official view of events while a Commune television is set up to provide the perspectives of the Paris rebels. On a stage-like set, more than 200 actors interpret characters of the Commune, especially the Popincourt neighbourhood in the XIth arrondissement. They voice their own thoughts and feelings concerning the social and political reforms. The scenes consist mainly of long camera takes.                                                                                                                                                                                                                                                                                         1
A kindergarten director Troshkin is a dead ringer for a criminal nicknamed "Docent" who stole the priceless...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             1
A man wakes up deep inside a cave. Suffering amnesia, he has no recollection of how he came to be here or of what happened to the man whose body he finds beside him. Tailed by a mysterious creature, he must continue through this strange and fantastic world. Enclosed, Tolbiac has no other option to reach the surface than to use REZO ZERO, secret observing cells in this cemetery-like abandoned mine.                                                                                                                                                                                                                                                                                                                                                                           1
50 years after decriminalisation of homosexuality in the UK, director Daisy Asquith mines the jewels of the BFI archive to take us into the relationships, desires, fears and expressions of gay men and women in the 20th century.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1
Name: overview, Length: 44307, dtype: int64
object

0.0         34
0.0         32
1e-06       30
0.000844    26
1e-06       26
            ..
0.589948     1
8.307719     1
1.806613     1
3.553427     1
0.163015     1
Name: popularity, Length: 44176, dtype: int64
object

/5D7UBSEgdyONE6Lql6xS7s6OLcW.jpg    5
/qW1oQlOHizRHXZQrpkimYr0oxzn.jpg    4
/2kslZXOaW0HmnGuVPCnQlCdXFR9.jpg    4
/8VSZ9coCzxOCW2wE2Qene1H1fKO.jpg    3
/cdwVC18URfEdQjjxqJyRMoGDC0H.jpg    3
                                   ..
/cFEFSq05bWXP0WhHWwpsbailJkl.jpg    1
/gDn14D7YuK4u2VPVzjg3510yV7C.jpg    1
/hy51EWjDmVmq4TO7GD542GLhux6.jpg    1
/tZhTYAs3rE3fmtz4XtLCAWzuwZ9.jpg    1
/s5UkZt6NTsrS7ZF0Rh8nzupRlIU.jpg    1
Name: poster_path, Length: 45024, dtype: int64
object

                                                                                                                                              11875
Metro-Goldwyn-Mayer (MGM)                                                                                                                       742
Warner Bros.                                                                                                                                    540
Paramount Pictures                                                                                                                              505
Twentieth Century Fox Film Corporation                                                                                                          439
                                                                                                                                              ...
HBO Films|Moving Pictures                                                                                                                         1
BIM Distribuzione|Canal+|Alta Producción|Centre National de la Cinématographie (CNC)|Rézo Productions|Compagnie Eric Rohmer (CER)|Cinémage        1
Galatée Films|Novo Arturo Films|Constantin Film Produktion|Pathé|France 2 Cinéma|France 3 Cinema|Logline Studios|Blue Screen Productions          1
Fox Searchlight Pictures|26 Films                                                                                                                 1
Yermoliev                                                                                                                                         1
Name: production_companies, Length: 22673, dtype: int64
object

United States of America                17851
                                         6282
United Kingdom                           2238
France                                   1654
Japan                                    1356
                                        ...
Australia|South Africa                      1
Romania|United Kingdom|Canada               1
Finland|Germany|Netherlands                 1
France|Denmark|Spain|Sweden                 1
Egypt|Italy|United States of America        1
Name: production_countries, Length: 2393, dtype: int64
object

2008-01-01    136
2009-01-01    121
2007-01-01    118
2005-01-01    111
2006-01-01    101
             ...
1957-09-26      1
1938-11-21      1
1936-08-19      1
2010-01-27      1
1917-10-21      1
Name: release_date, Length: 17336, dtype: int64
object

0.0           38052
12000000.0       20
11000000.0       19
10000000.0       19
2000000.0        18
              ...
36565280.0        1
439564.0          1
35610100.0        1
10217873.0        1
1413000.0         1
Name: revenue, Length: 6863, dtype: int64
float64

90.0     2556
0.0      1558
100.0    1470
95.0     1412
93.0     1214
         ...
410.0       1
283.0       1
238.0       1
566.0       1
780.0       1
Name: runtime, Length: 353, dtype: int64
float64

English                              22475
                                      3954
Français                              1860
日本語                                   1290
Italiano                              1220
                                     ...
普通话|English|日本語                          1
English|日本語|العربية|普通话                  1
Français|Latin||Português|English        1
Español|עִבְרִית|English                 1
Fulfulde|English                         1
Name: spoken_languages, Length: 1733, dtype: int64
object

Released           45014
Rumored              230
Post Production       98
In Production         20
Planned               15
Canceled               2
Name: status, dtype: int64
object

Based on a true story.                                        7
Be careful what you wish for.                                 4
Trust no one.                                                 4
-                                                             4
Classic Albums                                                3
                                                             ..
A special force in a special kind of hell!                    1
Play it. Sing it. Shout it. Feel it.                          1
If It's On TV, It Must Be The Truth.                          1
"I LOVE YOU BABY, BUT MY WIFE JUST REFUSES TO UNDERSTAND!"    1
A deadly game of wits.                                        1
Name: tagline, Length: 20283, dtype: int64
object

Cinderella              11
Hamlet                   9
Alice in Wonderland      9
Beauty and the Beast     8
Les Misérables           8
                        ..
Cluny Brown              1
Babies                   1
The Green Room           1
Captain Conan            1
Queerama                 1
Name: title, Length: 42277, dtype: int64
object

0.0    2998
6.0    2468
5.0    2001
7.0    1886
6.5    1722
       ...
9.4       3
9.6       1
9.8       1
0.7       1
1.1       1
Name: vote_average, Length: 92, dtype: int64
float64

1.0       3264
2.0       3132
0.0       2899
3.0       2787
4.0       2480
          ...
2755.0       1
1187.0       1
4200.0       1
3322.0       1
2712.0       1
Name: vote_count, Length: 1820, dtype: int64
float64

,belongs_to_collection,budget,genres,id,original_language,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,Toy Story Collection,30000000,Animation|Comedy|Family,862,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,Pixar Animation Studios,United States of America,1995-10-30,373554033.0,81.0,English,Released,NaN,Toy Story,7.7,5415.0
1,NaN,65000000,Adventure|Fantasy|Family,8844,en,When siblings Judy and Peter discover an encha...,17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,TriStar Pictures|Teitler Film|Interscope Commu...,United States of America,1995-12-15,262797249.0,104.0,English|Français,Released,Roll the dice and unleash the excitement!,Jumanji,6.9,2413.0
2,Grumpy Old Men Collection,0,Romance|Comedy,15602,en,A family wedding reignites the ancient feud be...,11.7129,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,Warner Bros.|Lancaster Gate,United States of America,1995-12-22,0.0,101.0,English,Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5,92.0
3,NaN,16000000,Comedy|Drama|Romance,31357,en,"Cheated on, mistreated and stepped on, the wom...",3.859495,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,Twentieth Century Fox Film Corporation,United States of America,1995-12-22,81452156.0,127.0,English,Released,Friends are the people who let you be yourself...,Waiting to Exhale,6.1,34.0
4,Father of the Bride Collection,0,Comedy,11862,en,Just when George Banks has recovered from his ...,8.387519,/e64sOI48hQXyru7naBFyssKFxVd.jpg,Sandollar Productions|Touchstone Pictures,United States of America,1995-02-10,76578911.0,106.0,English,Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,NaN,0,Drama|Family,439050,fa,Rising and falling between a man and woman.,0.072051,/jldsYflnId4tTWPx8es3uzsB1I8.jpg,NaN,Iran,NaN,0.0,90.0,فارسی,Released,Rising and falling between a man and woman,Subdue,4.0,1.0
45462,NaN,0,Drama,111109,tl,An artist struggles to finish his work while a...,0.178241,/xZkmxsNmYXJbKVsTRLLx3pqGHx7.jpg,Sine Olivia,Philippines,2011-11-17,0.0,360.0,NaN,Released,NaN,Century of Birthing,9.0,3.0
45463,NaN,0,Action|Drama|Thriller,67758,en,"When one of her hits goes wrong, a professiona...",0.903007,/d5bX92nDsISNhu3ZT69uHwmfCGw.jpg,American World Pictures,United States of America,2003-08-01,0.0,90.0,English,Released,A deadly game of wits.,Betrayal,3.8,6.0
45464,NaN,0,NaN,227506,en,"In a small town live two brothers, one a minis...",0.003503,/aorBPO7ak8e8iJKT5OcqYxU3jlK.jpg,Yermoliev,Russia,1917-10-21,0.0,87.0,NaN,Released,NaN,Satan Triumphant,0.0,0.0
45465,NaN,0,NaN,461257,en,50 years after decriminalisation of homosexual...,0.163015,/s5UkZt6NTsrS7ZF0Rh8nzupRlIU.jpg,NaN,United Kingdom,2017-06-09,0.0,75.0,English,Released,NaN,Queerama,0.0,0.0

## Cleaning Numerical Columns

10. __Convert__ the datatype in the columns __"budget"__, __"id"__ and __"popularity"__ __to numeric__. Set invalid values as NaN.

### Converting budget to numeric

In [37]:
df_flattened[~df_flattened['budget'].apply(lambda x: x.isdigit())]

,belongs_to_collection,budget,genres,id,original_language,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
19730,0.065736,/ff9qCepilowshEtG2GYWwzt2bs4.jpg,Carousel Productions|Vision View Entertainment...,1997-08-20,104.0,Released,NaN,Midnight Man,False,6.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29503,1.931659,/zV8bHuSL6WXoD6FWogP9j4x80bL.jpg,Aniplex|GoHands|BROSTA TV|Mardock Scramble Pro...,2012-09-29,68.0,Released,NaN,Mardock Scramble: The Third Exhaust,False,7.0,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35587,2.185485,/zaSf5OG7V8X8gqFvly88zDdRm46.jpg,Odyssey Media|Pulser Productions|Rogue State|T...,2014-01-01,82.0,Released,Beware Of Frost Bites,Avalanche Sharks,False,4.3,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
#Some rows have values shuffled across columns, so we are going to arrange them
#ONLY RUN THIS 1 TIME
indices_to_change=df_flattened[~df_flattened['budget'].apply(lambda x: x.isdigit())].index
columns_ordered=['budget','poster_path','production_companies','release_date','runtime','status','tagline','title','belongs_to_collection','vote_average', 'vote_count','spoken_languages',\
'revenue','production_countries','popularity','id','original_language','genres','overview']
for idx in indices_to_change:
    df_flattened.loc[idx,columns_ordered]=df_flattened.loc[idx,:].values

In [39]:
df_flattened.loc[indices_to_change]

,belongs_to_collection,budget,genres,id,original_language,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
19730,False,0.065736,NaN,NaN,NaN,NaN,NaN,/ff9qCepilowshEtG2GYWwzt2bs4.jpg,Carousel Productions|Vision View Entertainment...,NaN,1997-08-20,NaN,104.0,NaN,Released,NaN,Midnight Man,6.0,1
29503,False,1.931659,NaN,NaN,NaN,NaN,NaN,/zV8bHuSL6WXoD6FWogP9j4x80bL.jpg,Aniplex|GoHands|BROSTA TV|Mardock Scramble Pro...,NaN,2012-09-29,NaN,68.0,NaN,Released,NaN,Mardock Scramble: The Third Exhaust,7.0,12
35587,False,2.185485,NaN,NaN,NaN,NaN,NaN,/zaSf5OG7V8X8gqFvly88zDdRm46.jpg,Odyssey Media|Pulser Productions|Rogue State|T...,NaN,2014-01-01,NaN,82.0,NaN,Released,Beware Of Frost Bites,Avalanche Sharks,4.3,22

In [40]:
df_flattened['budget']=pd.to_numeric(df_flattened['budget'])
df_flattened['budget'].dtype

dtype('float64')

### Converting id to numeric

In [41]:
df_flattened['id']=pd.to_numeric(df_flattened['id'])
df_flattened['id'].dtype

dtype('float64')

### Converting popularity to numeric

In [42]:
df_flattened['popularity']=pd.to_numeric(df_flattened['popularity'])
df_flattened['popularity'].dtype

dtype('float64')

11. __Analyze__ the columns __"budget"__ and __"revenue"__ and __"runtime"__. Analyze movies with a budget/revenue/runtime of 0. Do you think the value 0 is the most appropriate value? __Take reasonable measures__!

In [43]:
df_flattened['budget'].replace(0.0,np.nan,inplace=True)
df_flattened['revenue'].replace(0.0,np.nan,inplace=True)
df_flattened['runtime'].replace(0.0,np.nan,inplace=True)

12. The columns "budget" and "revenue" shall show values in Million USD. __Convert and Overwrite__!

In [44]:
df_flattened['budget']=df_flattened['budget']/1000000
df_flattened['revenue']=df_flattened['revenue']/1000000

13. __Analyze__ movies with a __vote_count of 0__. What´s the __vote_average__ for those movies? Do you think this value is the most appropriate value? __Take reasonable measures__!

In [45]:
df_flattened.vote_average[(df_flattened.vote_count==0)].any() #Al menos es consistente que todos los vote_average son 0 para las pelis que no tienen ningún voto

False

In [48]:
df_flattened.loc[df_flattened['vote_count']==0,'vote_average']=np.nan

## Cleaning DateTime Columns

14. __Convert__ the datatype in the column __"release_date"__ __to datetime__. Set invalid values as NaN.

In [49]:
df_flattened['release_date']=pd.to_datetime(df_flattened['release_date'])

## Cleaning Text / String Columns

15. __Analyze__ the text columns "overview" and "tagline". Try to identify __missing data that is not represented by NaN__ (e.g. "No Data"). __Replace as NaN__ (np.nan)!

### cleaning overview

In [50]:
#check values of 3 words or less:
df_valid_overviews=df_flattened.copy()
df_overviews_str=df_valid_overviews[df_valid_overviews.overview.apply(lambda x: True if isinstance(x,str) else False)]
df_overviews_less_3=df_overviews_str[df_overviews_str.overview.apply(lambda x: True if len(x.split())<=3  else False)]
df_overviews_less_3.overview.value_counts().index

Index(['No overview found.', 'No Overview', ' ', 'Bollywood 2009',
       'No overview yet.', 'Feature film.', 'English gangster flick.',
       'Netflix Special', 'No overview.', 'Bigfoot documentary',
       'Plot unknown', 'x', 'Documentary', 'French Film', 'japanese movie',
       'Finnish documentary.', 'Tupla-Uuno', 'no overview yet',
       'Finnish Road Movie', 'No overview', 'A skeleton dances.',
       'American Documentary', '...', 'Discovery Channel documentary',
       'Return of Django', 'Directed by', 'Finnish Documentary',
       'Black and White', 'Not Available', 'German Comedy', 'Dom är tillbaka!',
       'Italian film', '2013 Italian comedy', 'No overview found',
       '70s Italian comedy.', 'Italian comedy', 'Scandal: Sex@students.edu'],
      dtype='object')

In [51]:
no_overview_pos=[0,1,2,4,8,10,11,17,19,22,25,28,33]
incorrect_overviews=df_overviews_less_3.overview.value_counts().index[no_overview_pos].to_list()
incorrect_overviews

['No overview found.',
 'No Overview',
 ' ',
 'No overview yet.',
 'No overview.',
 'Plot unknown',
 'x',
 'no overview yet',
 'No overview',
 '...',
 'Directed by',
 'Not Available',
 'No overview found']

In [52]:
ids_to_modify=df_overviews_str[df_overviews_str.overview.isin(incorrect_overviews)].index
ids_to_modify

Int64Index([  104,   800,   972,  1613,  2230,  3238,  3288,  3763,  4246,
             4538,
            ...
            43239, 43333, 43786, 43836, 44142, 44607, 45251, 45272, 45292,
            45433],
           dtype='int64', length=156)

In [53]:
df_valid_overviews.loc[ids_to_modify,'overview']=np.nan
df_valid_overviews

,belongs_to_collection,budget,genres,id,original_language,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,Toy Story Collection,30.0,Animation|Comedy|Family,862.0,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,Pixar Animation Studios,United States of America,1995-10-30,373.554033,81.0,English,Released,NaN,Toy Story,7.7,5415.0
1,NaN,65.0,Adventure|Fantasy|Family,8844.0,en,When siblings Judy and Peter discover an encha...,17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,TriStar Pictures|Teitler Film|Interscope Commu...,United States of America,1995-12-15,262.797249,104.0,English|Français,Released,Roll the dice and unleash the excitement!,Jumanji,6.9,2413.0
2,Grumpy Old Men Collection,NaN,Romance|Comedy,15602.0,en,A family wedding reignites the ancient feud be...,11.712900,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,Warner Bros.|Lancaster Gate,United States of America,1995-12-22,NaN,101.0,English,Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5,92.0
3,NaN,16.0,Comedy|Drama|Romance,31357.0,en,"Cheated on, mistreated and stepped on, the wom...",3.859495,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,Twentieth Century Fox Film Corporation,United States of America,1995-12-22,81.452156,127.0,English,Released,Friends are the people who let you be yourself...,Waiting to Exhale,6.1,34.0
4,Father of the Bride Collection,NaN,Comedy,11862.0,en,Just when George Banks has recovered from his ...,8.387519,/e64sOI48hQXyru7naBFyssKFxVd.jpg,Sandollar Productions|Touchstone Pictures,United States of America,1995-02-10,76.578911,106.0,English,Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,NaN,NaN,Drama|Family,439050.0,fa,Rising and falling between a man and woman.,0.072051,/jldsYflnId4tTWPx8es3uzsB1I8.jpg,NaN,Iran,NaT,NaN,90.0,فارسی,Released,Rising and falling between a man and woman,Subdue,4.0,1.0
45462,NaN,NaN,Drama,111109.0,tl,An artist struggles to finish his work while a...,0.178241,/xZkmxsNmYXJbKVsTRLLx3pqGHx7.jpg,Sine Olivia,Philippines,2011-11-17,NaN,360.0,NaN,Released,NaN,Century of Birthing,9.0,3.0
45463,NaN,NaN,Action|Drama|Thriller,67758.0,en,"When one of her hits goes wrong, a professiona...",0.903007,/d5bX92nDsISNhu3ZT69uHwmfCGw.jpg,American World Pictures,United States of America,2003-08-01,NaN,90.0,English,Released,A deadly game of wits.,Betrayal,3.8,6.0
45464,NaN,NaN,NaN,227506.0,en,"In a small town live two brothers, one a minis...",0.003503,/aorBPO7ak8e8iJKT5OcqYxU3jlK.jpg,Yermoliev,Russia,1917-10-21,NaN,87.0,NaN,Released,NaN,Satan Triumphant,NaN,0.0
45465,NaN,NaN,NaN,461257.0,en,50 years after decriminalisation of homosexual...,0.163015,/s5UkZt6NTsrS7ZF0Rh8nzupRlIU.jpg,NaN,United Kingdom,2017-06-09,NaN,75.0,English,Released,NaN,Queerama,NaN,0.0

### cleaning tagline

In [96]:
#Valid taglines are naturally short so it will need different tactics. 
#First we will check for very short ones to capture invalid taglines
df_valid_taglines=df_valid_overviews.copy()
df_taglines_str=df_valid_taglines[df_valid_taglines.tagline.apply(lambda x: True if isinstance(x,str) else False)]
df_taglines_less_3=df_taglines_str[(df_taglines_str.tagline.str.split().apply(len)<=2) & (df_taglines_str.tagline.str.len()<=15)]
df_taglines_less_3.tagline.unique()
# '   ' and '-' are the only invalid ones
incorrect_taglines=['-','   ']

In [97]:
#Now lets check for taglines that have the word 'no' to catch possible phrases like 'no data', etc
df_taglines_contains_no=df_taglines_str[(df_taglines_str.tagline.str.contains('No ', case=False)) & (df_taglines_str.tagline.str.split().apply(len)<=4)]
df_taglines_contains_no.tagline.unique()
#There are no taglines with 'no data' type of phrases

array(['There is no defense.', 'No Guards. No Walls.', 'Trust No One',
       "This Ain't No Game.", 'Trust no one.', 'Love knows no limits.',
       'Love Knows No Bounds.', 'Know life. No limits.',
       'Vengeance takes no prisoners.', 'There is no substitute.',
       'Passion has no limits', 'Vengeance knows no boundaries.',
       'No ordinary love story...', 'This is no game.',
       'No Money. Still Funny.', "It's no picnic!",
       'Leave No Man Behind.', 'No Soul Is Safe.', 'Hell hath no fury...',
       "It's No Laughing Matter.", 'No king rules forever.',
       'No Static At All!', 'No gut, no glory', 'No Sleep To Brooklyn!',
       'Desire knows no bounds.', 'Serve No Master', 'No day but today.',
       'Vengeance Knows No Mercy', 'Possession Knows No Bounds',
       'No Gut... No Glory.', 'Courage know no limit',
       'Americans...they have no imagination.', "...It's No Fairy Tale",
       'There is no escape.', 'No body is safe.', 'No goats. No glory.',
       'No experience necessary...', 'Survival is no game',
       'One Week, No Rules', "This Ain't No Hula!",
       'No pulse? No problem', 'Life Has No Recipe', 'No soul is safe.',
       'No one is safe', 'Take no prisoners.', 'No one is safe.',
       'No destiny', 'No Lifeguard on Duty', 'Do no harm.',
       'No Justice. No Peace.', 'No backstabbing. Just business',
       'SLO NO MO', "There's no parole...in Hell!!!",
       'No peace without justice...', 'No Plan is perfect',
       'Happiness has no formula.', 'Hell Hath No Fury',
       'Leave no loose ends', 'Trust no one', 'No more secrets.',
       'No turning back', 'No warning. No escape.', 'No system is safe.',
       'Love knows no borders.', 'Terror Has No Limits', 'Piano Forest',
       'Leave no soul unturned.', 'Possession Knows No Age',
       'No Ordinary Trifle', 'Revenge Has No Limits',
       'No sin goes unpunished', "There's no turning back",
       'Extinct no more!', 'Survival Is No Game', 'No One Is Save',
       'No kids allowed', 'No Regrets', 'No Escape',
       'No surrender for heroes.', 'Love knows no boundaries',
       'No rescue. No refuge.', 'No treason, no surrender.',
       'Danger knows no borders', 'No peace. No piece.', 'Long time no Z',
       'No evidence, no crime', 'No retreat. No surrender.',
       'Love needs no words', 'There is no antidote.',
       'No ordinary game!!!', 'Strictly no rules',
       'No más. No surrender.', 'No happy campers here...',
       'Love Has No Morals.', 'NO SOUL IS SAFE', "there's no going back",
       'All Southern, No Comfort.', 'He knows no fear...',
       'All guns. No control.', 'Family no more', 'Love has no rules.'],
      dtype=object)

In [98]:
ids_to_modify=df_taglines_less_3[df_taglines_less_3.tagline.isin(incorrect_taglines)].index
df_valid_taglines.loc[ids_to_modify,'tagline']=np.nan
df_valid_taglines

,belongs_to_collection,budget,genres,id,original_language,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,Toy Story Collection,30.0,Animation|Comedy|Family,862.0,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,Pixar Animation Studios,United States of America,1995-10-30,373.554033,81.0,English,Released,NaN,Toy Story,7.7,5415.0
1,NaN,65.0,Adventure|Fantasy|Family,8844.0,en,When siblings Judy and Peter discover an encha...,17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,TriStar Pictures|Teitler Film|Interscope Commu...,United States of America,1995-12-15,262.797249,104.0,English|Français,Released,Roll the dice and unleash the excitement!,Jumanji,6.9,2413.0
2,Grumpy Old Men Collection,NaN,Romance|Comedy,15602.0,en,A family wedding reignites the ancient feud be...,11.712900,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,Warner Bros.|Lancaster Gate,United States of America,1995-12-22,NaN,101.0,English,Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5,92.0
3,NaN,16.0,Comedy|Drama|Romance,31357.0,en,"Cheated on, mistreated and stepped on, the wom...",3.859495,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,Twentieth Century Fox Film Corporation,United States of America,1995-12-22,81.452156,127.0,English,Released,Friends are the people who let you be yourself...,Waiting to Exhale,6.1,34.0
4,Father of the Bride Collection,NaN,Comedy,11862.0,en,Just when George Banks has recovered from his ...,8.387519,/e64sOI48hQXyru7naBFyssKFxVd.jpg,Sandollar Productions|Touchstone Pictures,United States of America,1995-02-10,76.578911,106.0,English,Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,NaN,NaN,Drama|Family,439050.0,fa,Rising and falling between a man and woman.,0.072051,/jldsYflnId4tTWPx8es3uzsB1I8.jpg,NaN,Iran,NaT,NaN,90.0,فارسی,Released,Rising and falling between a man and woman,Subdue,4.0,1.0
45462,NaN,NaN,Drama,111109.0,tl,An artist struggles to finish his work while a...,0.178241,/xZkmxsNmYXJbKVsTRLLx3pqGHx7.jpg,Sine Olivia,Philippines,2011-11-17,NaN,360.0,NaN,Released,NaN,Century of Birthing,9.0,3.0
45463,NaN,NaN,Action|Drama|Thriller,67758.0,en,"When one of her hits goes wrong, a professiona...",0.903007,/d5bX92nDsISNhu3ZT69uHwmfCGw.jpg,American World Pictures,United States of America,2003-08-01,NaN,90.0,English,Released,A deadly game of wits.,Betrayal,3.8,6.0
45464,NaN,NaN,NaN,227506.0,en,"In a small town live two brothers, one a minis...",0.003503,/aorBPO7ak8e8iJKT5OcqYxU3jlK.jpg,Yermoliev,Russia,1917-10-21,NaN,87.0,NaN,Released,NaN,Satan Triumphant,NaN,0.0
45465,NaN,NaN,NaN,461257.0,en,50 years after decriminalisation of homosexual...,0.163015,/s5UkZt6NTsrS7ZF0Rh8nzupRlIU.jpg,NaN,United Kingdom,2017-06-09,NaN,75.0,English,Released,NaN,Queerama,NaN,0.0

## Removing Duplicates

16. __Identify__ and __remove__ duplicates!

In [99]:
df_valid_taglines[df_valid_taglines.duplicated(keep=False, subset='id')]

,belongs_to_collection,budget,genres,id,original_language,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
676,NaN,NaN,Drama|Romance,105045.0,de,"East-Berlin, 1961, shortly after the erection ...",0.122178,/5WFIrBhOOgc0jGmoLxMZwWqCctO.jpg,Studio Babelsberg|Centre National de la Cinéma...,Germany,1995-02-16,NaN,115.0,Deutsch,Released,"A love, a hope, a wall.",The Promise,5.0,1.0
838,NaN,NaN,Drama,132641.0,ja,"Ten years into a marriage, the wife is disappo...",0.096079,/z9WiHt5uQjs8L8tyBpRBKzlheF2.jpg,Toho Company,Japan,1953-04-29,NaN,89.0,日本語,Released,NaN,Wife,NaN,0.0
949,NaN,0.000004,Drama|Romance|War,22649.0,en,British nurse Catherine Barkley (Helen Hayes) ...,1.914697,/k0MF0IIbJ2PfOIku2KyraXL72d8.jpg,Paramount Pictures,United States of America,1932-12-08,0.000025,89.0,English,Released,Every woman who has loved will understand,A Farewell to Arms,6.2,29.0
1465,NaN,NaN,Drama|Romance,105045.0,de,"East-Berlin, 1961, shortly after the erection ...",0.122178,/5WFIrBhOOgc0jGmoLxMZwWqCctO.jpg,Studio Babelsberg|Centre National de la Cinéma...,Germany,1995-02-16,NaN,115.0,Deutsch,Released,"A love, a hope, a wall.",The Promise,5.0,1.0
2564,NaN,NaN,Documentary,84198.0,en,"Using personal stories, this powerful document...",0.501046,/jn8L1QdWWX5c0NUOLjzaSXtZrbt.jpg,NaN,United States of America,2012-03-22,NaN,84.0,English,Released,One Nation. Underfed.,A Place at the Table,6.9,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40040,NaN,0.980000,Drama|Fantasy,298721.0,th,"In a hospital, ten soldiers are being treated ...",2.535419,/5GasjPRAy5rlEyDOH7MeOyxyQGX.jpg,"Match Factory, The|Louverture Films|Tordenfilm...",United Kingdom|United States of America|France...,2015-09-02,NaN,122.0,English|ภาษาไทย,Released,NaN,Cemetery of Splendour,4.4,50.0
40276,NaN,NaN,Comedy,97995.0,en,"After breaking a mirror in his home, superstit...",0.141558,/4J6Ai4C5YRgfRUTlirrJ7QsmJKU.jpg,Max Linder Productions,United States of America,1921-02-06,NaN,62.0,English,Released,NaN,Seven Years Bad Luck,5.6,4.0
44821,Pokémon Collection,16.000000,Adventure|Fantasy|Animation|Action|Family,10991.0,ja,When Molly Hale's sadness of her father's disa...,6.480376,/5ILjS6XB5deiHop8SXPsYxXWVPE.jpg,TV Tokyo|4 Kids Entertainment|Nintendo|Pikachu...,Japan,2000-07-08,68.411275,93.0,English,Released,Pokémon: Spell of the Unknown,Pokémon: Spell of the Unknown,6.0,144.0
44826,Pokémon Collection,NaN,Adventure|Fantasy|Animation|Science Fiction|Fa...,12600.0,ja,"All your favorite Pokémon characters are back,...",6.080108,/bqL0PVHbQ8Jmw3Njcl38kW0CoeM.jpg,NaN,Japan|United States of America,2001-07-06,28.023563,75.0,日本語,Released,NaN,Pokémon 4Ever: Celebi - Voice of the Forest,5.7,82.0
45265,NaN,NaN,Comedy|Drama,265189.0,sv,"While holidaying in the French Alps, a Swedish...",12.165685,/rGMtc9AtZsnWSSL5VnLaGvx1PI6.jpg,Motlys|Coproduction Office|Film i Väst,Norway|Sweden|France,2014-08-15,1.359497,118.0,Français|Norsk|svenska|English,Released,NaN,Force Majeure,6.8,255.0

In [100]:
df_no_duplicates=df_valid_taglines[~df_valid_taglines.duplicated(keep='first',subset='id')]
df_no_duplicates

,belongs_to_collection,budget,genres,id,original_language,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,Toy Story Collection,30.0,Animation|Comedy|Family,862.0,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,Pixar Animation Studios,United States of America,1995-10-30,373.554033,81.0,English,Released,NaN,Toy Story,7.7,5415.0
1,NaN,65.0,Adventure|Fantasy|Family,8844.0,en,When siblings Judy and Peter discover an encha...,17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,TriStar Pictures|Teitler Film|Interscope Commu...,United States of America,1995-12-15,262.797249,104.0,English|Français,Released,Roll the dice and unleash the excitement!,Jumanji,6.9,2413.0
2,Grumpy Old Men Collection,NaN,Romance|Comedy,15602.0,en,A family wedding reignites the ancient feud be...,11.712900,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,Warner Bros.|Lancaster Gate,United States of America,1995-12-22,NaN,101.0,English,Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5,92.0
3,NaN,16.0,Comedy|Drama|Romance,31357.0,en,"Cheated on, mistreated and stepped on, the wom...",3.859495,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,Twentieth Century Fox Film Corporation,United States of America,1995-12-22,81.452156,127.0,English,Released,Friends are the people who let you be yourself...,Waiting to Exhale,6.1,34.0
4,Father of the Bride Collection,NaN,Comedy,11862.0,en,Just when George Banks has recovered from his ...,8.387519,/e64sOI48hQXyru7naBFyssKFxVd.jpg,Sandollar Productions|Touchstone Pictures,United States of America,1995-02-10,76.578911,106.0,English,Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,NaN,NaN,Drama|Family,439050.0,fa,Rising and falling between a man and woman.,0.072051,/jldsYflnId4tTWPx8es3uzsB1I8.jpg,NaN,Iran,NaT,NaN,90.0,فارسی,Released,Rising and falling between a man and woman,Subdue,4.0,1.0
45462,NaN,NaN,Drama,111109.0,tl,An artist struggles to finish his work while a...,0.178241,/xZkmxsNmYXJbKVsTRLLx3pqGHx7.jpg,Sine Olivia,Philippines,2011-11-17,NaN,360.0,NaN,Released,NaN,Century of Birthing,9.0,3.0
45463,NaN,NaN,Action|Drama|Thriller,67758.0,en,"When one of her hits goes wrong, a professiona...",0.903007,/d5bX92nDsISNhu3ZT69uHwmfCGw.jpg,American World Pictures,United States of America,2003-08-01,NaN,90.0,English,Released,A deadly game of wits.,Betrayal,3.8,6.0
45464,NaN,NaN,NaN,227506.0,en,"In a small town live two brothers, one a minis...",0.003503,/aorBPO7ak8e8iJKT5OcqYxU3jlK.jpg,Yermoliev,Russia,1917-10-21,NaN,87.0,NaN,Released,NaN,Satan Triumphant,NaN,0.0
45465,NaN,NaN,NaN,461257.0,en,50 years after decriminalisation of homosexual...,0.163015,/s5UkZt6NTsrS7ZF0Rh8nzupRlIU.jpg,NaN,United Kingdom,2017-06-09,NaN,75.0,English,Released,NaN,Queerama,NaN,0.0

## Handling Missing Values & Removing Observations

17. __Drop__ all rows/movies with unknown __id__ or __title__.

In [101]:
#Unknown ids
df_no_duplicates[df_no_duplicates.id.isna()]

,belongs_to_collection,budget,genres,id,original_language,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
19730,False,6.573600e-08,NaN,NaN,NaN,NaN,NaN,/ff9qCepilowshEtG2GYWwzt2bs4.jpg,Carousel Productions|Vision View Entertainment...,NaN,1997-08-20,NaN,104.0,NaN,Released,NaN,Midnight Man,6.0,1

In [102]:
#Unknown titles
df_no_duplicates[df_no_duplicates.title.isna()]

,belongs_to_collection,budget,genres,id,original_language,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
19729,NaN,NaN,Action|Thriller|Drama,82663.0,en,British soldiers force a recently captured IRA...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29502,Mardock Scramble Collection,NaN,Animation|Science Fiction,122662.0,ja,Third film of the Mardock Scramble series.,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35586,NaN,NaN,TV Movie|Action|Horror|Science Fiction,249260.0,en,A group of skiers are terrorized during spring...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

18. __Keep__ only those rows/movies in the df with __10 or more non-NaN__ values.

In [103]:
df_dropped_ids=df_no_duplicates.dropna(subset='id')
df_dropped_title=df_dropped_ids.dropna(subset='title')
df_dropped_title

,belongs_to_collection,budget,genres,id,original_language,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,Toy Story Collection,30.0,Animation|Comedy|Family,862.0,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,Pixar Animation Studios,United States of America,1995-10-30,373.554033,81.0,English,Released,NaN,Toy Story,7.7,5415.0
1,NaN,65.0,Adventure|Fantasy|Family,8844.0,en,When siblings Judy and Peter discover an encha...,17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,TriStar Pictures|Teitler Film|Interscope Commu...,United States of America,1995-12-15,262.797249,104.0,English|Français,Released,Roll the dice and unleash the excitement!,Jumanji,6.9,2413.0
2,Grumpy Old Men Collection,NaN,Romance|Comedy,15602.0,en,A family wedding reignites the ancient feud be...,11.712900,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,Warner Bros.|Lancaster Gate,United States of America,1995-12-22,NaN,101.0,English,Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5,92.0
3,NaN,16.0,Comedy|Drama|Romance,31357.0,en,"Cheated on, mistreated and stepped on, the wom...",3.859495,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,Twentieth Century Fox Film Corporation,United States of America,1995-12-22,81.452156,127.0,English,Released,Friends are the people who let you be yourself...,Waiting to Exhale,6.1,34.0
4,Father of the Bride Collection,NaN,Comedy,11862.0,en,Just when George Banks has recovered from his ...,8.387519,/e64sOI48hQXyru7naBFyssKFxVd.jpg,Sandollar Productions|Touchstone Pictures,United States of America,1995-02-10,76.578911,106.0,English,Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,NaN,NaN,Drama|Family,439050.0,fa,Rising and falling between a man and woman.,0.072051,/jldsYflnId4tTWPx8es3uzsB1I8.jpg,NaN,Iran,NaT,NaN,90.0,فارسی,Released,Rising and falling between a man and woman,Subdue,4.0,1.0
45462,NaN,NaN,Drama,111109.0,tl,An artist struggles to finish his work while a...,0.178241,/xZkmxsNmYXJbKVsTRLLx3pqGHx7.jpg,Sine Olivia,Philippines,2011-11-17,NaN,360.0,NaN,Released,NaN,Century of Birthing,9.0,3.0
45463,NaN,NaN,Action|Drama|Thriller,67758.0,en,"When one of her hits goes wrong, a professiona...",0.903007,/d5bX92nDsISNhu3ZT69uHwmfCGw.jpg,American World Pictures,United States of America,2003-08-01,NaN,90.0,English,Released,A deadly game of wits.,Betrayal,3.8,6.0
45464,NaN,NaN,NaN,227506.0,en,"In a small town live two brothers, one a minis...",0.003503,/aorBPO7ak8e8iJKT5OcqYxU3jlK.jpg,Yermoliev,Russia,1917-10-21,NaN,87.0,NaN,Released,NaN,Satan Triumphant,NaN,0.0
45465,NaN,NaN,NaN,461257.0,en,50 years after decriminalisation of homosexual...,0.163015,/s5UkZt6NTsrS7ZF0Rh8nzupRlIU.jpg,NaN,United Kingdom,2017-06-09,NaN,75.0,English,Released,NaN,Queerama,NaN,0.0

## Final (Cleaning) Steps

19. __Keep__ only those rows/movies in the df with __status "Released"__. Then __drop__ the column "status".

In [109]:
df_released=df_dropped_title[df_dropped_title.status=='Released'].copy()
df_released.drop('status', axis=1, inplace=True)
df_released

,belongs_to_collection,budget,genres,id,original_language,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,tagline,title,vote_average,vote_count
0,Toy Story Collection,30.0,Animation|Comedy|Family,862.0,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,Pixar Animation Studios,United States of America,1995-10-30,373.554033,81.0,English,NaN,Toy Story,7.7,5415.0
1,NaN,65.0,Adventure|Fantasy|Family,8844.0,en,When siblings Judy and Peter discover an encha...,17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,TriStar Pictures|Teitler Film|Interscope Commu...,United States of America,1995-12-15,262.797249,104.0,English|Français,Roll the dice and unleash the excitement!,Jumanji,6.9,2413.0
2,Grumpy Old Men Collection,NaN,Romance|Comedy,15602.0,en,A family wedding reignites the ancient feud be...,11.712900,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,Warner Bros.|Lancaster Gate,United States of America,1995-12-22,NaN,101.0,English,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5,92.0
3,NaN,16.0,Comedy|Drama|Romance,31357.0,en,"Cheated on, mistreated and stepped on, the wom...",3.859495,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,Twentieth Century Fox Film Corporation,United States of America,1995-12-22,81.452156,127.0,English,Friends are the people who let you be yourself...,Waiting to Exhale,6.1,34.0
4,Father of the Bride Collection,NaN,Comedy,11862.0,en,Just when George Banks has recovered from his ...,8.387519,/e64sOI48hQXyru7naBFyssKFxVd.jpg,Sandollar Productions|Touchstone Pictures,United States of America,1995-02-10,76.578911,106.0,English,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,NaN,NaN,Drama|Family,439050.0,fa,Rising and falling between a man and woman.,0.072051,/jldsYflnId4tTWPx8es3uzsB1I8.jpg,NaN,Iran,NaT,NaN,90.0,فارسی,Rising and falling between a man and woman,Subdue,4.0,1.0
45462,NaN,NaN,Drama,111109.0,tl,An artist struggles to finish his work while a...,0.178241,/xZkmxsNmYXJbKVsTRLLx3pqGHx7.jpg,Sine Olivia,Philippines,2011-11-17,NaN,360.0,NaN,NaN,Century of Birthing,9.0,3.0
45463,NaN,NaN,Action|Drama|Thriller,67758.0,en,"When one of her hits goes wrong, a professiona...",0.903007,/d5bX92nDsISNhu3ZT69uHwmfCGw.jpg,American World Pictures,United States of America,2003-08-01,NaN,90.0,English,A deadly game of wits.,Betrayal,3.8,6.0
45464,NaN,NaN,NaN,227506.0,en,"In a small town live two brothers, one a minis...",0.003503,/aorBPO7ak8e8iJKT5OcqYxU3jlK.jpg,Yermoliev,Russia,1917-10-21,NaN,87.0,NaN,NaN,Satan Triumphant,NaN,0.0
45465,NaN,NaN,NaN,461257.0,en,50 years after decriminalisation of homosexual...,0.163015,/s5UkZt6NTsrS7ZF0Rh8nzupRlIU.jpg,NaN,United Kingdom,2017-06-09,NaN,75.0,English,NaN,Queerama,NaN,0.0

20. The Order of the columns should be as follows:

In [110]:
ordered_columns=["id", "title", "tagline", "release_date", "genres", "belongs_to_collection", 
"original_language", "budget_musd", "revenue_musd", "production_companies",
"production_countries", "vote_count", "vote_average", "popularity", "runtime",
"overview", "spoken_languages", "poster_path"]

In [111]:
df_released.rename(columns={'budget':'budget_musd','revenue':'revenue_musd'}, inplace=True)
df_released=df_released[ordered_columns]
df_released

,id,title,tagline,release_date,genres,belongs_to_collection,original_language,budget_musd,revenue_musd,production_companies,production_countries,vote_count,vote_average,popularity,runtime,overview,spoken_languages,poster_path
0,862.0,Toy Story,NaN,1995-10-30,Animation|Comedy|Family,Toy Story Collection,en,30.0,373.554033,Pixar Animation Studios,United States of America,5415.0,7.7,21.946943,81.0,"Led by Woody, Andy's toys live happily in his ...",English,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg
1,8844.0,Jumanji,Roll the dice and unleash the excitement!,1995-12-15,Adventure|Fantasy|Family,NaN,en,65.0,262.797249,TriStar Pictures|Teitler Film|Interscope Commu...,United States of America,2413.0,6.9,17.015539,104.0,When siblings Judy and Peter discover an encha...,English|Français,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg
2,15602.0,Grumpier Old Men,Still Yelling. Still Fighting. Still Ready for...,1995-12-22,Romance|Comedy,Grumpy Old Men Collection,en,NaN,NaN,Warner Bros.|Lancaster Gate,United States of America,92.0,6.5,11.712900,101.0,A family wedding reignites the ancient feud be...,English,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg
3,31357.0,Waiting to Exhale,Friends are the people who let you be yourself...,1995-12-22,Comedy|Drama|Romance,NaN,en,16.0,81.452156,Twentieth Century Fox Film Corporation,United States of America,34.0,6.1,3.859495,127.0,"Cheated on, mistreated and stepped on, the wom...",English,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg
4,11862.0,Father of the Bride Part II,Just When His World Is Back To Normal... He's ...,1995-02-10,Comedy,Father of the Bride Collection,en,NaN,76.578911,Sandollar Productions|Touchstone Pictures,United States of America,173.0,5.7,8.387519,106.0,Just when George Banks has recovered from his ...,English,/e64sOI48hQXyru7naBFyssKFxVd.jpg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,439050.0,Subdue,Rising and falling between a man and woman,NaT,Drama|Family,NaN,fa,NaN,NaN,NaN,Iran,1.0,4.0,0.072051,90.0,Rising and falling between a man and woman.,فارسی,/jldsYflnId4tTWPx8es3uzsB1I8.jpg
45462,111109.0,Century of Birthing,NaN,2011-11-17,Drama,NaN,tl,NaN,NaN,Sine Olivia,Philippines,3.0,9.0,0.178241,360.0,An artist struggles to finish his work while a...,NaN,/xZkmxsNmYXJbKVsTRLLx3pqGHx7.jpg
45463,67758.0,Betrayal,A deadly game of wits.,2003-08-01,Action|Drama|Thriller,NaN,en,NaN,NaN,American World Pictures,United States of America,6.0,3.8,0.903007,90.0,"When one of her hits goes wrong, a professiona...",English,/d5bX92nDsISNhu3ZT69uHwmfCGw.jpg
45464,227506.0,Satan Triumphant,NaN,1917-10-21,NaN,NaN,en,NaN,NaN,Yermoliev,Russia,0.0,NaN,0.003503,87.0,"In a small town live two brothers, one a minis...",NaN,/aorBPO7ak8e8iJKT5OcqYxU3jlK.jpg
45465,461257.0,Queerama,NaN,2017-06-09,NaN,NaN,en,NaN,NaN,NaN,United Kingdom,0.0,NaN,0.163015,75.0,50 years after decriminalisation of homosexual...,English,/s5UkZt6NTsrS7ZF0Rh8nzupRlIU.jpg

21. __Reset__ the Index and create a __RangeIndex__.

In [112]:
df_released.reset_index(inplace=True, drop=True)
df_released.index

RangeIndex(start=0, stop=44985, step=1)

22. __Save__ the cleaned dataset in a __csv-file__.

In [114]:
df_released.to_csv('clean_movies_dataset.csv')